# Generated by Django 6.0.5 on 2026-09-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed Payment'), ('REFUNDED', 'Refunded'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20),
        ),
    ]
