# Generated by Django 6.0.5 on 2026-10-10 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_cancellation_reason_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='badge_label',
            field=models.CharField(blank=True, default='Master Artisan', max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='cover_banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='craft_story',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='materials_used',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='techniques_used',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='workshop_headline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='WorkshopPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workshops/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_photos', to='products.sellerprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
