# Generated by Django 6.0.5 on 2026-10-10 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_sellerprofile_badge_label_sellerprofile_cover_banner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('PROCESSING', 'Processing Transfer'), ('PAID', 'Paid / Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('payout_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer (NEFT/IMPS)'), ('UPI', 'UPI Direct'), ('STRIPE', 'Stripe Connect')], default='BANK_TRANSFER', max_length=30)),
                ('account_details', models.TextField(help_text='Account number, IFSC, or UPI ID')),
                ('reference_id', models.CharField(blank=True, default='', help_text='Transaction reference / UTR / Transfer ID', max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_payouts', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('SALE', 'Gross Order Sale'), ('COMMISSION', 'Platform Commission Fee'), ('REFUND', 'Customer Refund Deduction'), ('PAYOUT', 'Payout Disbursement'), ('ADJUSTMENT', 'Balance Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_credit', models.BooleanField(help_text='True if adds to seller balance, False if deducts')),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Running available balance after this entry', max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='products.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='products.sellerpayout')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
