# Generated by Django 6.0.5 on 2026-10-10 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_sellerpayout_sellerledgerentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PRODUCT_MODERATION', 'Product Moderation'), ('SELLER_APPROVAL', 'Seller Approval & Status'), ('COMMISSION_CHANGE', 'Commission Rate Change'), ('DISPUTE_RESOLUTION', 'Dispute Resolution'), ('PAYOUT_DECISION', 'Payout Decision'), ('REFUND_DECISION', 'Refund & Return Decision'), ('CATEGORY_MANAGEMENT', 'Category Management'), ('OTHER', 'General Admin Action')], max_length=40)),
                ('target_model', models.CharField(max_length=60)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('target_repr', models.CharField(blank=True, default='', max_length=255)),
                ('action_summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformMonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('PAYMENT_FAILURE', 'Payment Failure'), ('WEBHOOK_ERROR', 'Stripe Webhook Error'), ('GATEWAY_ANOMALY', 'Payment Gateway Anomaly'), ('SYSTEM_ERROR', 'Platform System Error')], max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical Alert')], default='ERROR', max_length=20)),
                ('source', models.CharField(help_text='e.g. Stripe Webhook, Payment Intent, Checkout Session', max_length=100)),
                ('event_id', models.CharField(blank=True, default='', help_text='Session ID, Event ID, or Gateway Intent ID', max_length=150)),
                ('customer_email', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_logs', to='products.order')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_monitoring_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
